### PR TITLE
Add support for golang legacy mutex profiles

### PR DESCRIPTION
**Pull request by rauls5382**
This corresponds to golang/go change 29650.

### CODE REVIEW

**Comment by dgryski** [comment]
You can use `https://golang.org/cl/29650` as a short link to the CL.

**Comment by hyangah** [comment]
Thanks -- There are some more commits that need to be upstreamed. Do you want to add others in  separate PRs? Here is the list of commits committed locally in the go repo.

src/internal/pprof/profile:
b079869dad 2016-11-29T18:04:37+00:00 internal/pprof/profile: parse mutex profile including comments
f7c351bdf6 2016-11-28T21:52:15+00:00 internal/pprof: don't discard allocations called by reflect.Call
682ffae6db 2016-11-02T19:09:11+00:00 internal/pprof/profile: new package, moved from cmd/internal/pprof/profile
ca922b6d36 2016-10-28T11:47:16+00:00 runtime: Profile goroutines holding contended mutexes.
1441f76938 2016-04-15T02:32:10+00:00 cmd: remove unnecessary type conversions
da6205b67e 2016-04-13T17:22:38+00:00 cmd/pprof/internal/profile: always subtract 1 from PCs
204b6f48c5 2016-04-12T15:02:28+00:00 cmd/pprof/internal: move to cmd/internal/pprof
fcd2a06ab6 2016-03-28T22:55:20+00:00 cmd/pprof/internal: use and accept packed encoding for repeated fields
5fea2ccc77 2016-03-02T00:13:47+00:00 all: single space after period.
e0c05fcb5b 2015-12-05T04:01:28+00:00 cmd/pprof/internal: map/slice literals janitoring
7f9f70e5b6 2015-06-11T14:18:57+00:00 all: fix misprints in comments
1831e1ec37 2015-06-02T05:25:52+00:00 cmd/pprof/internal/profile: fix missing error check
19354b9dc8 2015-05-18T19:36:41+00:00 cmd/pprof/internal/profile: ignore comments when parsing heap profiles
14a4649fe2 2015-04-26T20:12:17+00:00 cmd/pprof: handle empty profile gracefully
8e2a57e643 2015-03-16T23:07:15+00:00 cmd/pprof/internal/profile: insert blank line after non-doc comment
8b5221a57b 2014-09-30T13:41:54-04:00 cmd/pprof: add Go implementation

src/cmd/pprof/internal:
1486585400 39366326cc 2017-02-08T20:23:20+00:00 net/http/pprof: return error when requested profile duration exceeds WriteTimeout
1485983404 5b1c6efb31 2017-02-01T21:10:04+00:00 cmd/pprof: remove redundant URLs from error messages in fetch.FetchURL
1482446624 8887be4654 2016-12-22T22:43:44+00:00 cmd/pprof: Re-enable weblist and disasm
1481813737 7e4ef4ebfc 2016-12-15T14:55:37+00:00 cmd/pprof: search for sample types in profile
1481239357 4c4201f0e2 2016-12-08T23:22:37+00:00 all: make spelling consistent
1478975415 2f497263e4 2016-11-12T18:30:15+00:00 cmd/pprof: add options to skip tls verification
1478875661 c439a5d8b7 2016-11-11T14:47:41+00:00 cmd/pprof: don't print binary outputs in interactive mode
1478183231 89ccd5795c 2016-11-03T14:27:11+00:00 cmd/pprof: use correct default handler for Go programs
1478113761 d5b97f614e 2016-11-02T19:09:21+00:00 cmd/pprof: move cmd/internal/pprof back to cmd/pprof/internal
1478113751 682ffae6db 2016-11-02T19:09:11+00:00 internal/pprof/profile: new package, moved from cmd/internal/pprof/profile
1476238152 0aadaf2ad5 2016-10-12T02:09:12+00:00 cmd/pprof: instruction-level granularity in callgrind output
1473877593 33ed356475 2016-09-14T18:26:33+00:00 cmd: add internal/browser package
1463068710 376e641540 2016-05-12T15:58:30+00:00 cmd: fixed certain vet warnings
1462991107 e9407ae514 2016-05-11T18:25:07+00:00 cmd/pprof: remove tempDir when no longer needed
1460490729 da224a5c42 2016-04-12T19:52:09+00:00 cmd/pprof: pass the event to pprof_toggle_asm for the weblist command
1460473348 204b6f48c5 2016-04-12T15:02:28+00:00 cmd/pprof/internal: move to cmd/internal/pprof
1458887293 fdba5a7544 2016-03-25T06:28:13+00:00 all: delete dead non-test code
1457901496 69f49e1cbc 2016-03-13T20:38:16+00:00 cmd/pprof: fix crash with invalid source
1456877627 5fea2ccc77 2016-03-02T00:13:47+00:00 all: single space after period.
1456339349 fdd0179bb1 2016-02-24T18:42:29+00:00 all: fix typos and spelling
1450370308 7688f0d9fb 2015-12-17T16:38:28+00:00 cmd/pprof: fix scaling of "gigabyte" unit
1437623499 3bab4ef68d 2015-07-23T03:51:39+00:00 cmd/pprof: fix race between viewer and web command
1436934650 505f6e335e 2015-07-15T04:30:50+00:00 cmd/pprof: store temporary files in temporary directory
1436934635 2bd1e5e50b 2015-07-15T04:30:35+00:00 cmd/pprof: run $BROWSER and system browser before Chrome
1434032337 7f9f70e5b6 2015-06-11T14:18:57+00:00 all: fix misprints in comments
1433478960 14da5bef5f 2015-06-05T04:36:00+00:00 cmd/pprof: use copy of svgpan library instead of link to remote site
1430079137 14a4649fe2 2015-04-26T20:12:17+00:00 cmd/pprof: handle empty profile gracefully
1424375180 d384545a45 2015-02-19T19:46:20+00:00 cmd/pprof: add -runtime flag
1423596779 85cae5d7b8 2015-02-10T19:32:59+00:00 cmd/pprof/internal/report: fix typo in recognized output unit
1418311398 3fa5d3a6dc 2014-12-11T15:23:18+00:00 cmd/pprof: remove -show_bytes from command line help
1417710263 c9d0c81214 2014-12-04T11:24:23-05:00 cmd/pprof/internal/commands: add command to open browser on windows
1417634040 9f04a62a39 2014-12-03T14:14:00-05:00 cmd/pprof: fix symbol resolution for remote profiles
1416253481 38fef031e1 2014-11-17T14:44:41-05:00 cmd/pprof: fix EOF handling when getting function source
1412098914 8b5221a57b 2014-09-30T13:41:54-04:00 cmd/pprof: add Go implementation

**Comment by rauls5382** [comment]
Are you aware of any individual commits that need to be upstreamed? I randomly selected a few of these and they had been upstreamed already.

I only found 39366326cc pending (which was committed today!). I think we should upstream that separately, and stop committing changes to golang pprof until the merge is completed.

**Comment by hyangah** [comment]
I went through changes submitted in 2016-2017.
In addition to 39366326cc

https://go-review.googlesource.com/33454
https://go-review.googlesource.com/29650 (this one)
https://go-review.googlesource.com/34147 (spelling)
https://go-review.googlesource.com/#/c/33157/
https://go-review.googlesource.com/#/c/31123/
https://go-review.googlesource.com/23019/  (not sure if it's still relevant)

**Comment by rauls5382** [comment]
Thanks, Hana. I'll look at those and create commits for them if appropriate.
Alex, can you please review and merge this one?

**Pull request merged**
