### PR TITLE
internal/driver: fix spelling in help text

### PR DESCRIPTION
**Pull request by dgryski**

### CODE REVIEW

**Comment by rauls5382** [comment]
Thanks for the patch. 

In order to accept your patch, I need you to sign the Google CLA, at https://cla.developers.google.com/about/google-individual

**Comment by dgryski** [comment]
I've already signed it for my patches in Go: https://github.com/golang/go/blob/master/AUTHORS#L154

**Comment by rauls5382** [comment]
The tool we use to check for CLAs can't find your github account.

It could be because the email address used to sign the CLA is not associated to your github account.
Can you add it if it isn't there? It doesn't have to be the primary email on the account.

Thanks

**Comment by dgryski** [comment]
It already is :/ Both dgryski@gmail.com and damian@gryski.com are in my profile.

**Comment by dgryski** [comment]
I have just set my Gmail to be the primary public email address for my account.

**Comment by rauls5382** [comment]
Thanks. Sorry for the churn. I checked and it is OK as is. I'll merge the pull request.

Also, if you want, you can login to cla.developers.google.com and add your github account to your existing CLA. But it's not strictly necessary.

**Pull request merged**
