### PR TITLE
*: golint, go tool vet, unsued, gosimple, staticcheck

### PR DESCRIPTION
**Pull request by tamird**
Ran a few linters and corrected various problems.

Would you guys be open to adding a .travis.yml to run these linters (and the tests)?

### CODE REVIEW

**Comment by aalexand** [comment]
Can you resolve the conflicts?

What's the travis configuration one would use for these?

**Comment by tamird** [comment]
@aalexand resolved conflicts and added the travis checks; can you take a look?

**Comment by aalexand** [comment]
Sorry for the delay. This looks good to me but I wanted @rauls5382 to take a look. But let's go ahead with this, we can fix in posterity.

**Comment by tamird** [comment]
Thanks for the approval! You'll still have to merge this on my behalf, though.

**Pull request merged**
