### PR TITLE
Update demangle dependency

### PR DESCRIPTION
**Pull request by romange**
Newer demangle version fixes bugs related to C++ templates

### CODE REVIEW

**Comment by romange** [comment]
Specifically, the current version (2018) can not demangle this string
`_ZN3fu27abi_4006detail12type_erasure16invocation_table14function_traitIFvvEE16internal_invokerINS2_3boxILb0EZN4util5uring8Proactor10AwaitBriefIZN5sider6Engine3SetERKSt6vectorIN4absl14lts_2020_09_234SpanIcEESaISJ_EEPNSD_14CommandContextEEUlvE_EEDTclfp_EEOT_EUlvE_SaISU_EEELb0EE6invokeEPNS2_13data_accessorEm`

**Comment by kalyanac** [comment]
Thank you for the PR. I will merge it after the tests pass, one test failed due to unrelated reasons.

**Comment by aalexand** [comment]
@kalyanac AFAICT all tests are passing now.

**Review by kalyanac — APPROVED** [review]

**Comment by kalyanac** [comment]
Thank you for the ping. I just restarted the failed test on Travis after I posted the message.

**Pull request merged**
