### PR TITLE
Fixing comment in dotColor function.

### PR DESCRIPTION
**Pull request by yarchi**
Providing score -1 actually returns green not red. Conversely, 1 returns red.
See lines 375 and 378. r = 1 + saturation*score is r = 1 - saturation if score == -1. Thus, r decreases and g < r.

### CODE REVIEW

**Comment by yarchi** [comment]
@googlebot I signed it!

**Comment by kalyanac** [comment]
@wyk9787 Can you check why the Windows tests are failing?

**Comment by yarchi** [comment]
It says:
`
ok  	github.com/google/pprof/profile	0.073s
?   	github.com/google/pprof/third_party/d3	[no test files]
?   	github.com/google/pprof/third_party/d3flamegraph	[no test files]
?   	github.com/google/pprof/third_party/svgpan	[no test files]
FAIL
`
Looks like the reason that this three folders don't have corresponding unit tests.

**Review by wyk9787 — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
