### PR TITLE
Drop XCode 8.3

### PR DESCRIPTION
**Pull request by kalyanac**
Dropping XCode 8.3 per offline discussion with @aalexand

### CODE REVIEW

**Comment by aalexand** [comment]
@kalyanac Could you check whether the travis CI config is in sync with the XCode versions used for OSX testing by build.golang.org? And bring it in sync if there is a trivial way to do so (i.e. if needed versions are supported by Travis CI). We've been trying to be in sync with that so that vendoring pprof into golang does not bring up failing tests.

**Comment by kalyanac** [comment]
it looks like they only test against
10.10 (Yosemite), 10.11 (El Capitan), and 10.12 (Sierra). 

> We only have builders for 10.10, 10.11 and 10.12 as of 2019-01-11.

Additional information here:
https://github.com/golang/go/wiki/MinimumRequirements#macos-n%C3%A9e-os-x-aka-darwin

They dont yet support 10.14. 

The support matrix is here:
https://github.com/golang/go/wiki/Darwin

We can identify failing tests and skip them on unsupported OS X versions to address the failing tests on older OS X versions. It will add maintenance burden though.

**Comment by aalexand** [comment]
@kalyanac Versioning of XCode vs. OSX is a bit confusing here. With this PR we'll test xcode9.4 and xcode10.1 which is according to https://docs.travis-ci.com/user/reference/osx/#macos-version are both macOS 10.13. Excluding xcode8.3 we'll stop testing macOS 10.12. Is that OK?

It's also not clear which XCode versions the golang builders use.

I am basically cautious about two things:

1) If you want to drop support for xcode8.3 because some test can't be made passing for it, then when pprof gets vendored into golang the test will fail if golang builders use xcode 8.3.
2) Generally having too much disjoint environments with golang builders may cause some bugs to slip through and only manifest when we vendor pprof into golang tree. We had some history on that, see #146, #156, #255.

**Comment by kalyanac** [comment]
It is not clear what XCode versions golang builders are using. However, it is a good estimate that the latest XCode that can be run on 10.12.6 is 9.2. ref: https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_10.x_(since_Free_On-Device_Development). 

We can make disassembly work with 8.3 but it will introduce small but version specific code paths. Also disassembly of large binaries maybe slower due to lack of `--start-address` & `--stop-address` in objdump.

I was leaning towards minimizing version specific code paths in the code and also becasue XCode 8.3 is pretty old, but the benefits of working well within golang verndoring is important as evident from the issues you linked.

With the above caveats, I can change #449 and drop this PR.

**Comment by aalexand** [comment]
The easiest for now might be to check explicitly in the test if objdump supports these flags and t.Skip() the test if not. I am not a fan of this added complexity either, just want to make sure the future vendoring of pprof goes smooth. For large binaries - that's if we try to emulate the absent flags? I wouldn't go there, I think it's reasonable to require that objdump has to be of specific version or newer and skip the test otherwise.

BTW, #338 is similar in spirit.

**Pull request closed without merging**
